- hosts: 127.0.0.1
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: install base packages
      apt: pkg={{ item }} install_recommends=no
      with_items:
        - ruby
        - build-essential
        - patch
        - nginx
        - git
        - unzip
        - nodejs
        - ruby-dev
        - zlib1g-dev
        - liblzma-dev
        - zlib1g-dev
        - libfreetype6-dev

    - name: install rbenv
      become: true
      become_user: vagrant
      git:
        repo: https://github.com/rbenv/rbenv.git
        dest: ~/.rbenv

    - name: install ruby-build
      become: true
      become_user: vagrant
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build

    - name: add rbenv path to .bashrc
      lineinfile: dest=/home/vagrant/.bashrc line="export PATH="$HOME/.rbenv/bin:$PATH""

    - name: load rbenv in .bashrc
      lineinfile: dest=/home/vagrant/.bashrc line="eval \"$(rbenv init -)\""

    - name: install Ruby 2.4.4
      become: true
      become_user: vagrant
      shell: ~/.rbenv/bin/rbenv install 2.4.4
      args:
        creates: ~/.rbenv/versions/2.4.4

    - name: make Ruby 2.4.4 the default
      become: true
      become_user: vagrant
      shell: ~/.rbenv/bin/rbenv global 2.4.4

    - name: install bundler
      become: true
      become_user: vagrant
      shell: ~/.rbenv/bin/rbenv exec gem install bundler

    - name: rbenv rehash
      become: true
      become_user: vagrant
      shell: ~/.rbenv/bin/rbenv rehash

    - name: copy default nginx config
      copy: src=nginx-default dest=/etc/nginx/sites-available/default owner=root group=root
      register: nginx_default

    - name: restart nginx service
      service: name=nginx state=restarted
      when: nginx_default.changed

    - name: start nginx service
      service: name=nginx state=started enabled=yes

    - name: symlink open-review-toolkit to /vagrant
      file: src=/vagrant dest=/home/vagrant/open-review-toolkit state=link owner=vagrant group=vagrant

    - name: add cd command to .bashrc
      lineinfile: dest=/home/vagrant/.bashrc line="cd open-review-toolkit/"

    - name: add cabal/bin path to .bashrc
      lineinfile: dest=/home/vagrant/.bashrc line="export PATH=$PATH:$HOME/.cabal/bin"

    - name: create .bundle directory
      file: path=/home/vagrant/.bundle state=directory owner=vagrant group=vagrant

    - name: copy bundler config
      copy: src=bundle.config dest=/home/vagrant/.bundle/config owner=vagrant group=vagrant

    - bundler: state=present chdir=/vagrant executable=~/.rbenv/versions/2.4.4/bin/bundle
      become: true
      become_user: vagrant

    - name: install latex
      apt: name=texlive,texlive-latex-extra,texlive-xetex,fonts-wqy-zenhei,lmodern state=present install_recommends=no

    - name: copy updated longtable
      # File generated by applying longtable.sty.patch to longtable.sty.orig.
      copy: src=longtable.sty dest=/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty

    - name: add updated haskell repo key
      apt_key: keyserver=keyserver.ubuntu.com id=063DAB2BDC0B3F9FCEBC378BFF3AEACEF6F88286
    - name: add updated haskell repo
      apt_repository: repo='deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main' state=present

    - name: install haskell
      apt: name=ghc-8.4.2 state=present
    - name: install cabal
      apt: name=cabal-install-2.2 state=present

    - name: update cabal
      command: cabal update creates=~/.cabal/packages/
      environment:
        PATH: "{{ ansible_env.PATH }}:/opt/ghc/8.4.2/bin:/opt/cabal/2.2/bin"
      become: yes
      become_user: vagrant

    - name: install cabal packages
      shell: cabal install Cabal-2.2.0.1 pandoc-2.2 pandoc-crossref pandoc-citeproc pandoc-citeproc-preamble pandoc-sidenote
      environment:
        PATH: "{{ ansible_env.PATH }}:/opt/ghc/8.4.2/bin:/opt/cabal/2.2/bin"
      become: yes
      become_user: vagrant

    - name: Clean up apt
      apt:
        autoremove: yes
        autoclean: yes
