- hosts: 127.0.0.1
  tasks:
    - name: install base packages
      apt: pkg={{ item }} install_recommends=no
      with_items:
        - ruby
        - bundler
        - build-essential
        - patch
        - nginx
        - git
        - nodejs
        - ruby-dev
        - zlib1g-dev
        - liblzma-dev
        - zlib1g-dev
        - libfreetype6-dev

    - name: copy default nginx config
      copy: src=nginx-default dest=/etc/nginx/sites-available/default owner=root group=root
      register: nginx_default

    - name: restart nginx service
      service: name=nginx state=restarted
      when: nginx_default.changed

    - name: start nginx service
      service: name=nginx state=started enabled=yes

    - name: symlink open-review-toolkit to /vagrant
      file: src=/vagrant dest=/home/vagrant/open-review-toolkit state=link owner=vagrant group=vagrant

    - name: add cd command to .bashrc
      lineinfile: dest=/home/vagrant/.bashrc line="cd open-review-toolkit/"

    - name: add path update to .profile
      lineinfile: dest=/home/vagrant/.profile line="PATH=$PATH:$HOME/.cabal/bin"

    - name: create .bundle directory
      file: path=/home/vagrant/.bundle state=directory owner=vagrant group=vagrant

    - name: copy bundler config
      copy: src=bundle.config dest=/home/vagrant/.bundle/config owner=vagrant group=vagrant

    - bundler: state=present chdir=/vagrant
      become: true
      become_user: vagrant

    - name: install latex
      apt: name=texlive,texlive-latex-extra,lmodern state=present install_recommends=no

    - name: copy updated longtable
      # File generated by applying longtable.sty.patch to longtable.sty.orig.
      copy: src=longtable.sty dest=/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty

    - name: add updated haskell repo key
      apt_key: keyserver=keyserver.ubuntu.com id=063DAB2BDC0B3F9FCEBC378BFF3AEACEF6F88286
    - name: add updated haskell repo
      apt_repository: repo='deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main' state=present

    - name: install haskell
      apt: name=ghc-7.10.3 state=present
    - name: install cabal
      apt: name=cabal-install-1.24 state=present

    - name: update cabal
      command: cabal update creates=~/.cabal/packages/
      environment:
        PATH: "{{ ansible_env.PATH }}:/opt/ghc/7.10.3/bin:/opt/cabal/1.24/bin"
      become: yes
      become_user: vagrant

    - name: install cabal packages
      shell: cabal install pandoc-1.17.0.2 pandoc-crossref-0.2.1.3 pandoc-citeproc-0.10.1 pandoc-citeproc-preamble-1.0.0
      environment:
        PATH: "{{ ansible_env.PATH }}:/opt/ghc/7.10.3/bin:/opt/cabal/1.24/bin"
      become: yes
      become_user: vagrant
